---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
if (!file.exists("activity.csv") )
{
    dlurl <- 'http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip'  
    download.file(dlurl,destfile='repdata%2Fdata%2Factivity.zip',mode='wb')  
    unzip('repdata%2Fdata%2Factivity.zip')
    
}
data <- read.csv("activity.csv")


## What is mean total number of steps taken per day?
steps_by_day <- aggregate(steps ~ date, data, sum)
hist(steps_by_day$steps, main = paste("Total number of steps everyday"), col="blue",xlab="Number of Steps")
rmean <- mean(steps_by_day$steps)
rmean
rmedian <- median(steps_by_day$steps)
rmedian

## What is the average daily activity pattern?
steps_by_interval <- aggregate(steps ~ interval, data, mean)
plot(steps_by_interval$interval,steps_by_interval$steps, type="l", xlab="Interval", ylab="No. of Steps",main="Average daily activity pattern by Interval")
max_interval <- steps_by_interval[which.max(steps_by_interval$steps),1]
max_interval

## Imputing missing values
NATotal <- sum(!complete.cases(data))
NATotal
# mean is now used to compute missing values
StepsAverage <- aggregate(steps ~ interval, data = data, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(data)) {
    obs <- data[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(StepsAverage, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    fillNA <- c(fillNA, steps)
}
#Create a new dataset including the imputed missing values
new_activity <- data
new_activity$steps <- fillNA
#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day.

StepsTotalUnion <- aggregate(steps ~ date, data = new_activity, sum, na.rm = TRUE)
hist(StepsTotalUnion$steps, main = paste("Total Steps Everyday"), col="red", xlab="No. of Steps")
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), col="pink", xlab="No. of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("red", "pink"), lwd=10)

rmeantotal <- mean(StepsTotalUnion$steps)
rmeantotal
rmediantotal <- median(StepsTotalUnion$steps)
rmediantotal

rmediandiff <- rmediantotal - rmedian
rmediandiff
rmeandiff <- rmeantotal - rmean
rmeandiff

#On observation the impact of the missing data has the biggest effect on the 10000 - 150000 step interval and changes frequency from 27.5 to 35 a variance of 7.5


## Are there differences in activity patterns between weekdays and weekends?

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
new_activity$dow = as.factor(ifelse(is.element(weekdays(as.Date(new_activity$date)),weekdays), "Weekday", "Weekend"))
StepsTotalUnion <- aggregate(steps ~ interval + dow, new_activity, mean)
library(lattice)
xyplot(StepsTotalUnion$steps ~ StepsTotalUnion$interval|StepsTotalUnion$dow, main="Average Steps per Day by Interval",xlab="Intervals", ylab="No of Steps",layout=c(1,2), type="l")



